/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.xpiping.notificationcenter.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the QueuedEmail service. Represents a row in the &quot;xpiping_notificationcenter_QueuedEmail&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ndjangui.notificationcenter.model.impl.QueuedEmailModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ndjangui.notificationcenter.model.impl.QueuedEmailImpl}.
 * </p>
 *
 * @author marcoleo
 * @see QueuedEmail
 * @see com.ndjangui.notificationcenter.model.impl.QueuedEmailImpl
 * @see com.ndjangui.notificationcenter.model.impl.QueuedEmailModelImpl
 * @generated
 */
public interface QueuedEmailModel extends BaseModel<QueuedEmail> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a queued email model instance should use the {@link QueuedEmail} interface instead.
	 */

	/**
	 * Returns the primary key of this queued email.
	 *
	 * @return the primary key of this queued email
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this queued email.
	 *
	 * @param primaryKey the primary key of this queued email
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the queued email ID of this queued email.
	 *
	 * @return the queued email ID of this queued email
	 */
	public long getQueuedEmailId();

	/**
	 * Sets the queued email ID of this queued email.
	 *
	 * @param queuedEmailId the queued email ID of this queued email
	 */
	public void setQueuedEmailId(long queuedEmailId);

	/**
	 * Returns the company ID of this queued email.
	 *
	 * @return the company ID of this queued email
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this queued email.
	 *
	 * @param companyId the company ID of this queued email
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this queued email.
	 *
	 * @return the create date of this queued email
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this queued email.
	 *
	 * @param createDate the create date of this queued email
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this queued email.
	 *
	 * @return the modified date of this queued email
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this queued email.
	 *
	 * @param modifiedDate the modified date of this queued email
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the from of this queued email.
	 *
	 * @return the from of this queued email
	 */
	@AutoEscape
	public String getFrom();

	/**
	 * Sets the from of this queued email.
	 *
	 * @param from the from of this queued email
	 */
	public void setFrom(String from);

	/**
	 * Returns the from name of this queued email.
	 *
	 * @return the from name of this queued email
	 */
	@AutoEscape
	public String getFromName();

	/**
	 * Sets the from name of this queued email.
	 *
	 * @param fromName the from name of this queued email
	 */
	public void setFromName(String fromName);

	/**
	 * Returns the to of this queued email.
	 *
	 * @return the to of this queued email
	 */
	@AutoEscape
	public String getTo();

	/**
	 * Sets the to of this queued email.
	 *
	 * @param to the to of this queued email
	 */
	public void setTo(String to);

	/**
	 * Returns the to name of this queued email.
	 *
	 * @return the to name of this queued email
	 */
	@AutoEscape
	public String getToName();

	/**
	 * Sets the to name of this queued email.
	 *
	 * @param toName the to name of this queued email
	 */
	public void setToName(String toName);

	/**
	 * Returns the cc of this queued email.
	 *
	 * @return the cc of this queued email
	 */
	@AutoEscape
	public String getCc();

	/**
	 * Sets the cc of this queued email.
	 *
	 * @param cc the cc of this queued email
	 */
	public void setCc(String cc);

	/**
	 * Returns the bcc of this queued email.
	 *
	 * @return the bcc of this queued email
	 */
	@AutoEscape
	public String getBcc();

	/**
	 * Sets the bcc of this queued email.
	 *
	 * @param bcc the bcc of this queued email
	 */
	public void setBcc(String bcc);

	/**
	 * Returns the subject of this queued email.
	 *
	 * @return the subject of this queued email
	 */
	@AutoEscape
	public String getSubject();

	/**
	 * Sets the subject of this queued email.
	 *
	 * @param subject the subject of this queued email
	 */
	public void setSubject(String subject);

	/**
	 * Returns the body of this queued email.
	 *
	 * @return the body of this queued email
	 */
	@AutoEscape
	public String getBody();

	/**
	 * Sets the body of this queued email.
	 *
	 * @param body the body of this queued email
	 */
	public void setBody(String body);

	/**
	 * Returns the attachment file name of this queued email.
	 *
	 * @return the attachment file name of this queued email
	 */
	@AutoEscape
	public String getAttachmentFileName();

	/**
	 * Sets the attachment file name of this queued email.
	 *
	 * @param attachmentFileName the attachment file name of this queued email
	 */
	public void setAttachmentFileName(String attachmentFileName);

	/**
	 * Returns the attachment file entry ID of this queued email.
	 *
	 * @return the attachment file entry ID of this queued email
	 */
	public long getAttachmentFileEntryId();

	/**
	 * Sets the attachment file entry ID of this queued email.
	 *
	 * @param attachmentFileEntryId the attachment file entry ID of this queued email
	 */
	public void setAttachmentFileEntryId(long attachmentFileEntryId);

	/**
	 * Returns the sent tries of this queued email.
	 *
	 * @return the sent tries of this queued email
	 */
	public long getSentTries();

	/**
	 * Sets the sent tries of this queued email.
	 *
	 * @param sentTries the sent tries of this queued email
	 */
	public void setSentTries(long sentTries);

	/**
	 * Returns the sent on of this queued email.
	 *
	 * @return the sent on of this queued email
	 */
	public Date getSentOn();

	/**
	 * Sets the sent on of this queued email.
	 *
	 * @param sentOn the sent on of this queued email
	 */
	public void setSentOn(Date sentOn);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(QueuedEmail queuedEmail);

	@Override
	public int hashCode();

	@Override
	public CacheModel<QueuedEmail> toCacheModel();

	@Override
	public QueuedEmail toEscapedModel();

	@Override
	public QueuedEmail toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}