/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ndjangui.notificationcenter.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.xpiping.notificationcenter.model.QueuedEmail;
import com.xpiping.notificationcenter.service.QueuedEmailLocalServiceUtil;

/**
 * The extended model base implementation for the QueuedEmail service. Represents a row in the &quot;xpiping_notificationcenter_QueuedEmail&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link QueuedEmailImpl}.
 * </p>
 *
 * @author marcoleo
 * @see QueuedEmailImpl
 * @see com.xpiping.notificationcenter.model.QueuedEmail
 * @generated
 */
public abstract class QueuedEmailBaseImpl extends QueuedEmailModelImpl
	implements QueuedEmail {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a queued email model instance should use the {@link QueuedEmail} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			QueuedEmailLocalServiceUtil.addQueuedEmail(this);
		}
		else {
			QueuedEmailLocalServiceUtil.updateQueuedEmail(this);
		}
	}
}