/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package cmr.fandenatech.ndjangui.model.impl;

import cmr.fandenatech.ndjangui.model.FundType;
import cmr.fandenatech.ndjangui.service.FundTypeLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the FundType service. Represents a row in the &quot;ndjangui_FundType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FundTypeImpl}.
 * </p>
 *
 * @author guyw
 * @see FundTypeImpl
 * @see cmr.fandenatech.ndjangui.model.FundType
 * @generated
 */
public abstract class FundTypeBaseImpl extends FundTypeModelImpl
	implements FundType {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a fund type model instance should use the {@link FundType} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			FundTypeLocalServiceUtil.addFundType(this);
		}
		else {
			FundTypeLocalServiceUtil.updateFundType(this);
		}
	}
}