/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package cmr.fandenatech.ndjangui.model.impl;

import cmr.fandenatech.ndjangui.model.MemberSitting;
import cmr.fandenatech.ndjangui.model.MemberSittingModel;
import cmr.fandenatech.ndjangui.model.MemberSittingSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the MemberSitting service. Represents a row in the &quot;ndjangui_MemberSitting&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link cmr.fandenatech.ndjangui.model.MemberSittingModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MemberSittingImpl}.
 * </p>
 *
 * @author guyw
 * @see MemberSittingImpl
 * @see cmr.fandenatech.ndjangui.model.MemberSitting
 * @see cmr.fandenatech.ndjangui.model.MemberSittingModel
 * @generated
 */
@JSON(strict = true)
public class MemberSittingModelImpl extends BaseModelImpl<MemberSitting>
	implements MemberSittingModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a member sitting model instance should use the {@link cmr.fandenatech.ndjangui.model.MemberSitting} interface instead.
	 */
	public static final String TABLE_NAME = "ndjangui_MemberSitting";
	public static final Object[][] TABLE_COLUMNS = {
			{ "memberSittingId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "memberId", Types.BIGINT },
			{ "sittingId", Types.BIGINT },
			{ "memberName", Types.VARCHAR },
			{ "sittingName", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table ndjangui_MemberSitting (memberSittingId LONG not null primary key,userId LONG,groupId LONG,companyId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,memberId LONG,sittingId LONG,memberName VARCHAR(75) null,sittingName VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table ndjangui_MemberSitting";
	public static final String ORDER_BY_JPQL = " ORDER BY memberSitting.memberSittingId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY ndjangui_MemberSitting.memberSittingId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.cmr.fandenatech.ndjangui.model.MemberSitting"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.cmr.fandenatech.ndjangui.model.MemberSitting"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.cmr.fandenatech.ndjangui.model.MemberSitting"),
			true);
	public static long GROUPID_COLUMN_BITMASK = 1L;
	public static long SITTINGID_COLUMN_BITMASK = 2L;
	public static long MEMBERSITTINGID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static MemberSitting toModel(MemberSittingSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		MemberSitting model = new MemberSittingImpl();

		model.setMemberSittingId(soapModel.getMemberSittingId());
		model.setUserId(soapModel.getUserId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setMemberId(soapModel.getMemberId());
		model.setSittingId(soapModel.getSittingId());
		model.setMemberName(soapModel.getMemberName());
		model.setSittingName(soapModel.getSittingName());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<MemberSitting> toModels(MemberSittingSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<MemberSitting> models = new ArrayList<MemberSitting>(soapModels.length);

		for (MemberSittingSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.cmr.fandenatech.ndjangui.model.MemberSitting"));

	public MemberSittingModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _memberSittingId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMemberSittingId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _memberSittingId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MemberSitting.class;
	}

	@Override
	public String getModelClassName() {
		return MemberSitting.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("memberSittingId", getMemberSittingId());
		attributes.put("userId", getUserId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("memberId", getMemberId());
		attributes.put("sittingId", getSittingId());
		attributes.put("memberName", getMemberName());
		attributes.put("sittingName", getSittingName());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long memberSittingId = (Long)attributes.get("memberSittingId");

		if (memberSittingId != null) {
			setMemberSittingId(memberSittingId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long memberId = (Long)attributes.get("memberId");

		if (memberId != null) {
			setMemberId(memberId);
		}

		Long sittingId = (Long)attributes.get("sittingId");

		if (sittingId != null) {
			setSittingId(sittingId);
		}

		String memberName = (String)attributes.get("memberName");

		if (memberName != null) {
			setMemberName(memberName);
		}

		String sittingName = (String)attributes.get("sittingName");

		if (sittingName != null) {
			setSittingName(sittingName);
		}
	}

	@JSON
	@Override
	public long getMemberSittingId() {
		return _memberSittingId;
	}

	@Override
	public void setMemberSittingId(long memberSittingId) {
		_memberSittingId = memberSittingId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getMemberId() {
		return _memberId;
	}

	@Override
	public void setMemberId(long memberId) {
		_memberId = memberId;
	}

	@JSON
	@Override
	public long getSittingId() {
		return _sittingId;
	}

	@Override
	public void setSittingId(long sittingId) {
		_columnBitmask |= SITTINGID_COLUMN_BITMASK;

		if (!_setOriginalSittingId) {
			_setOriginalSittingId = true;

			_originalSittingId = _sittingId;
		}

		_sittingId = sittingId;
	}

	public long getOriginalSittingId() {
		return _originalSittingId;
	}

	@JSON
	@Override
	public String getMemberName() {
		if (_memberName == null) {
			return StringPool.BLANK;
		}
		else {
			return _memberName;
		}
	}

	@Override
	public void setMemberName(String memberName) {
		_memberName = memberName;
	}

	@JSON
	@Override
	public String getSittingName() {
		if (_sittingName == null) {
			return StringPool.BLANK;
		}
		else {
			return _sittingName;
		}
	}

	@Override
	public void setSittingName(String sittingName) {
		_sittingName = sittingName;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			MemberSitting.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MemberSitting toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (MemberSitting)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MemberSittingImpl memberSittingImpl = new MemberSittingImpl();

		memberSittingImpl.setMemberSittingId(getMemberSittingId());
		memberSittingImpl.setUserId(getUserId());
		memberSittingImpl.setGroupId(getGroupId());
		memberSittingImpl.setCompanyId(getCompanyId());
		memberSittingImpl.setUserName(getUserName());
		memberSittingImpl.setCreateDate(getCreateDate());
		memberSittingImpl.setModifiedDate(getModifiedDate());
		memberSittingImpl.setMemberId(getMemberId());
		memberSittingImpl.setSittingId(getSittingId());
		memberSittingImpl.setMemberName(getMemberName());
		memberSittingImpl.setSittingName(getSittingName());

		memberSittingImpl.resetOriginalValues();

		return memberSittingImpl;
	}

	@Override
	public int compareTo(MemberSitting memberSitting) {
		long primaryKey = memberSitting.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof MemberSitting)) {
			return false;
		}

		MemberSitting memberSitting = (MemberSitting)obj;

		long primaryKey = memberSitting.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		MemberSittingModelImpl memberSittingModelImpl = this;

		memberSittingModelImpl._originalGroupId = memberSittingModelImpl._groupId;

		memberSittingModelImpl._setOriginalGroupId = false;

		memberSittingModelImpl._originalSittingId = memberSittingModelImpl._sittingId;

		memberSittingModelImpl._setOriginalSittingId = false;

		memberSittingModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<MemberSitting> toCacheModel() {
		MemberSittingCacheModel memberSittingCacheModel = new MemberSittingCacheModel();

		memberSittingCacheModel.memberSittingId = getMemberSittingId();

		memberSittingCacheModel.userId = getUserId();

		memberSittingCacheModel.groupId = getGroupId();

		memberSittingCacheModel.companyId = getCompanyId();

		memberSittingCacheModel.userName = getUserName();

		String userName = memberSittingCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			memberSittingCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			memberSittingCacheModel.createDate = createDate.getTime();
		}
		else {
			memberSittingCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			memberSittingCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			memberSittingCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		memberSittingCacheModel.memberId = getMemberId();

		memberSittingCacheModel.sittingId = getSittingId();

		memberSittingCacheModel.memberName = getMemberName();

		String memberName = memberSittingCacheModel.memberName;

		if ((memberName != null) && (memberName.length() == 0)) {
			memberSittingCacheModel.memberName = null;
		}

		memberSittingCacheModel.sittingName = getSittingName();

		String sittingName = memberSittingCacheModel.sittingName;

		if ((sittingName != null) && (sittingName.length() == 0)) {
			memberSittingCacheModel.sittingName = null;
		}

		return memberSittingCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{memberSittingId=");
		sb.append(getMemberSittingId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", memberId=");
		sb.append(getMemberId());
		sb.append(", sittingId=");
		sb.append(getSittingId());
		sb.append(", memberName=");
		sb.append(getMemberName());
		sb.append(", sittingName=");
		sb.append(getSittingName());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("cmr.fandenatech.ndjangui.model.MemberSitting");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>memberSittingId</column-name><column-value><![CDATA[");
		sb.append(getMemberSittingId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>memberId</column-name><column-value><![CDATA[");
		sb.append(getMemberId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sittingId</column-name><column-value><![CDATA[");
		sb.append(getSittingId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>memberName</column-name><column-value><![CDATA[");
		sb.append(getMemberName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sittingName</column-name><column-value><![CDATA[");
		sb.append(getSittingName());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = MemberSitting.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			MemberSitting.class
		};
	private long _memberSittingId;
	private long _userId;
	private String _userUuid;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private long _memberId;
	private long _sittingId;
	private long _originalSittingId;
	private boolean _setOriginalSittingId;
	private String _memberName;
	private String _sittingName;
	private long _columnBitmask;
	private MemberSitting _escapedModel;
}