/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package cmr.fandenatech.ndjangui.model.impl;

import cmr.fandenatech.ndjangui.model.Operation;
import cmr.fandenatech.ndjangui.service.OperationLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Operation service. Represents a row in the &quot;ndjangui_Operation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OperationImpl}.
 * </p>
 *
 * @author guyw
 * @see OperationImpl
 * @see cmr.fandenatech.ndjangui.model.Operation
 * @generated
 */
public abstract class OperationBaseImpl extends OperationModelImpl
	implements Operation {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a operation model instance should use the {@link Operation} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			OperationLocalServiceUtil.addOperation(this);
		}
		else {
			OperationLocalServiceUtil.updateOperation(this);
		}
	}
}