/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package cmr.fandenatech.ndjangui.model.impl;

import cmr.fandenatech.ndjangui.model.Sanction;
import cmr.fandenatech.ndjangui.model.SanctionModel;
import cmr.fandenatech.ndjangui.model.SanctionSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Sanction service. Represents a row in the &quot;ndjangui_Sanction&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link cmr.fandenatech.ndjangui.model.SanctionModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SanctionImpl}.
 * </p>
 *
 * @author guyw
 * @see SanctionImpl
 * @see cmr.fandenatech.ndjangui.model.Sanction
 * @see cmr.fandenatech.ndjangui.model.SanctionModel
 * @generated
 */
@JSON(strict = true)
public class SanctionModelImpl extends BaseModelImpl<Sanction>
	implements SanctionModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a sanction model instance should use the {@link cmr.fandenatech.ndjangui.model.Sanction} interface instead.
	 */
	public static final String TABLE_NAME = "ndjangui_Sanction";
	public static final Object[][] TABLE_COLUMNS = {
			{ "sanctionId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "memberId", Types.BIGINT },
			{ "budgetPeriodId", Types.BIGINT },
			{ "name", Types.VARCHAR },
			{ "shortDescription", Types.CLOB },
			{ "sanctionTypeId", Types.BIGINT },
			{ "sittingId", Types.BIGINT },
			{ "amount", Types.DOUBLE },
			{ "status", Types.INTEGER },
			{ "srcFundClassPK", Types.BIGINT },
			{ "srcFundClassName", Types.VARCHAR },
			{ "destFundClassPK", Types.BIGINT },
			{ "destFundClassName", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table ndjangui_Sanction (sanctionId LONG not null primary key,userId LONG,groupId LONG,companyId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,memberId LONG,budgetPeriodId LONG,name VARCHAR(75) null,shortDescription TEXT null,sanctionTypeId LONG,sittingId LONG,amount DOUBLE,status INTEGER,srcFundClassPK LONG,srcFundClassName VARCHAR(75) null,destFundClassPK LONG,destFundClassName VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table ndjangui_Sanction";
	public static final String ORDER_BY_JPQL = " ORDER BY sanction.sanctionId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY ndjangui_Sanction.sanctionId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.cmr.fandenatech.ndjangui.model.Sanction"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.cmr.fandenatech.ndjangui.model.Sanction"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.cmr.fandenatech.ndjangui.model.Sanction"),
			true);
	public static long GROUPID_COLUMN_BITMASK = 1L;
	public static long STATUS_COLUMN_BITMASK = 2L;
	public static long SANCTIONID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Sanction toModel(SanctionSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Sanction model = new SanctionImpl();

		model.setSanctionId(soapModel.getSanctionId());
		model.setUserId(soapModel.getUserId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setMemberId(soapModel.getMemberId());
		model.setBudgetPeriodId(soapModel.getBudgetPeriodId());
		model.setName(soapModel.getName());
		model.setShortDescription(soapModel.getShortDescription());
		model.setSanctionTypeId(soapModel.getSanctionTypeId());
		model.setSittingId(soapModel.getSittingId());
		model.setAmount(soapModel.getAmount());
		model.setStatus(soapModel.getStatus());
		model.setSrcFundClassPK(soapModel.getSrcFundClassPK());
		model.setSrcFundClassName(soapModel.getSrcFundClassName());
		model.setDestFundClassPK(soapModel.getDestFundClassPK());
		model.setDestFundClassName(soapModel.getDestFundClassName());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Sanction> toModels(SanctionSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Sanction> models = new ArrayList<Sanction>(soapModels.length);

		for (SanctionSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.cmr.fandenatech.ndjangui.model.Sanction"));

	public SanctionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _sanctionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSanctionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _sanctionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Sanction.class;
	}

	@Override
	public String getModelClassName() {
		return Sanction.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("sanctionId", getSanctionId());
		attributes.put("userId", getUserId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("memberId", getMemberId());
		attributes.put("budgetPeriodId", getBudgetPeriodId());
		attributes.put("name", getName());
		attributes.put("shortDescription", getShortDescription());
		attributes.put("sanctionTypeId", getSanctionTypeId());
		attributes.put("sittingId", getSittingId());
		attributes.put("amount", getAmount());
		attributes.put("status", getStatus());
		attributes.put("srcFundClassPK", getSrcFundClassPK());
		attributes.put("srcFundClassName", getSrcFundClassName());
		attributes.put("destFundClassPK", getDestFundClassPK());
		attributes.put("destFundClassName", getDestFundClassName());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long sanctionId = (Long)attributes.get("sanctionId");

		if (sanctionId != null) {
			setSanctionId(sanctionId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long memberId = (Long)attributes.get("memberId");

		if (memberId != null) {
			setMemberId(memberId);
		}

		Long budgetPeriodId = (Long)attributes.get("budgetPeriodId");

		if (budgetPeriodId != null) {
			setBudgetPeriodId(budgetPeriodId);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String shortDescription = (String)attributes.get("shortDescription");

		if (shortDescription != null) {
			setShortDescription(shortDescription);
		}

		Long sanctionTypeId = (Long)attributes.get("sanctionTypeId");

		if (sanctionTypeId != null) {
			setSanctionTypeId(sanctionTypeId);
		}

		Long sittingId = (Long)attributes.get("sittingId");

		if (sittingId != null) {
			setSittingId(sittingId);
		}

		Double amount = (Double)attributes.get("amount");

		if (amount != null) {
			setAmount(amount);
		}

		Integer status = (Integer)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}

		Long srcFundClassPK = (Long)attributes.get("srcFundClassPK");

		if (srcFundClassPK != null) {
			setSrcFundClassPK(srcFundClassPK);
		}

		String srcFundClassName = (String)attributes.get("srcFundClassName");

		if (srcFundClassName != null) {
			setSrcFundClassName(srcFundClassName);
		}

		Long destFundClassPK = (Long)attributes.get("destFundClassPK");

		if (destFundClassPK != null) {
			setDestFundClassPK(destFundClassPK);
		}

		String destFundClassName = (String)attributes.get("destFundClassName");

		if (destFundClassName != null) {
			setDestFundClassName(destFundClassName);
		}
	}

	@JSON
	@Override
	public long getSanctionId() {
		return _sanctionId;
	}

	@Override
	public void setSanctionId(long sanctionId) {
		_sanctionId = sanctionId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getMemberId() {
		return _memberId;
	}

	@Override
	public void setMemberId(long memberId) {
		_memberId = memberId;
	}

	@JSON
	@Override
	public long getBudgetPeriodId() {
		return _budgetPeriodId;
	}

	@Override
	public void setBudgetPeriodId(long budgetPeriodId) {
		_budgetPeriodId = budgetPeriodId;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@JSON
	@Override
	public String getShortDescription() {
		if (_shortDescription == null) {
			return StringPool.BLANK;
		}
		else {
			return _shortDescription;
		}
	}

	@Override
	public void setShortDescription(String shortDescription) {
		_shortDescription = shortDescription;
	}

	@JSON
	@Override
	public long getSanctionTypeId() {
		return _sanctionTypeId;
	}

	@Override
	public void setSanctionTypeId(long sanctionTypeId) {
		_sanctionTypeId = sanctionTypeId;
	}

	@JSON
	@Override
	public long getSittingId() {
		return _sittingId;
	}

	@Override
	public void setSittingId(long sittingId) {
		_sittingId = sittingId;
	}

	@JSON
	@Override
	public double getAmount() {
		return _amount;
	}

	@Override
	public void setAmount(double amount) {
		_amount = amount;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_columnBitmask |= STATUS_COLUMN_BITMASK;

		if (!_setOriginalStatus) {
			_setOriginalStatus = true;

			_originalStatus = _status;
		}

		_status = status;
	}

	public int getOriginalStatus() {
		return _originalStatus;
	}

	@JSON
	@Override
	public long getSrcFundClassPK() {
		return _srcFundClassPK;
	}

	@Override
	public void setSrcFundClassPK(long srcFundClassPK) {
		_srcFundClassPK = srcFundClassPK;
	}

	@JSON
	@Override
	public String getSrcFundClassName() {
		if (_srcFundClassName == null) {
			return StringPool.BLANK;
		}
		else {
			return _srcFundClassName;
		}
	}

	@Override
	public void setSrcFundClassName(String srcFundClassName) {
		_srcFundClassName = srcFundClassName;
	}

	@JSON
	@Override
	public long getDestFundClassPK() {
		return _destFundClassPK;
	}

	@Override
	public void setDestFundClassPK(long destFundClassPK) {
		_destFundClassPK = destFundClassPK;
	}

	@JSON
	@Override
	public String getDestFundClassName() {
		if (_destFundClassName == null) {
			return StringPool.BLANK;
		}
		else {
			return _destFundClassName;
		}
	}

	@Override
	public void setDestFundClassName(String destFundClassName) {
		_destFundClassName = destFundClassName;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Sanction.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Sanction toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Sanction)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SanctionImpl sanctionImpl = new SanctionImpl();

		sanctionImpl.setSanctionId(getSanctionId());
		sanctionImpl.setUserId(getUserId());
		sanctionImpl.setGroupId(getGroupId());
		sanctionImpl.setCompanyId(getCompanyId());
		sanctionImpl.setUserName(getUserName());
		sanctionImpl.setCreateDate(getCreateDate());
		sanctionImpl.setModifiedDate(getModifiedDate());
		sanctionImpl.setMemberId(getMemberId());
		sanctionImpl.setBudgetPeriodId(getBudgetPeriodId());
		sanctionImpl.setName(getName());
		sanctionImpl.setShortDescription(getShortDescription());
		sanctionImpl.setSanctionTypeId(getSanctionTypeId());
		sanctionImpl.setSittingId(getSittingId());
		sanctionImpl.setAmount(getAmount());
		sanctionImpl.setStatus(getStatus());
		sanctionImpl.setSrcFundClassPK(getSrcFundClassPK());
		sanctionImpl.setSrcFundClassName(getSrcFundClassName());
		sanctionImpl.setDestFundClassPK(getDestFundClassPK());
		sanctionImpl.setDestFundClassName(getDestFundClassName());

		sanctionImpl.resetOriginalValues();

		return sanctionImpl;
	}

	@Override
	public int compareTo(Sanction sanction) {
		long primaryKey = sanction.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Sanction)) {
			return false;
		}

		Sanction sanction = (Sanction)obj;

		long primaryKey = sanction.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		SanctionModelImpl sanctionModelImpl = this;

		sanctionModelImpl._originalGroupId = sanctionModelImpl._groupId;

		sanctionModelImpl._setOriginalGroupId = false;

		sanctionModelImpl._originalStatus = sanctionModelImpl._status;

		sanctionModelImpl._setOriginalStatus = false;

		sanctionModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Sanction> toCacheModel() {
		SanctionCacheModel sanctionCacheModel = new SanctionCacheModel();

		sanctionCacheModel.sanctionId = getSanctionId();

		sanctionCacheModel.userId = getUserId();

		sanctionCacheModel.groupId = getGroupId();

		sanctionCacheModel.companyId = getCompanyId();

		sanctionCacheModel.userName = getUserName();

		String userName = sanctionCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			sanctionCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			sanctionCacheModel.createDate = createDate.getTime();
		}
		else {
			sanctionCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			sanctionCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			sanctionCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		sanctionCacheModel.memberId = getMemberId();

		sanctionCacheModel.budgetPeriodId = getBudgetPeriodId();

		sanctionCacheModel.name = getName();

		String name = sanctionCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			sanctionCacheModel.name = null;
		}

		sanctionCacheModel.shortDescription = getShortDescription();

		String shortDescription = sanctionCacheModel.shortDescription;

		if ((shortDescription != null) && (shortDescription.length() == 0)) {
			sanctionCacheModel.shortDescription = null;
		}

		sanctionCacheModel.sanctionTypeId = getSanctionTypeId();

		sanctionCacheModel.sittingId = getSittingId();

		sanctionCacheModel.amount = getAmount();

		sanctionCacheModel.status = getStatus();

		sanctionCacheModel.srcFundClassPK = getSrcFundClassPK();

		sanctionCacheModel.srcFundClassName = getSrcFundClassName();

		String srcFundClassName = sanctionCacheModel.srcFundClassName;

		if ((srcFundClassName != null) && (srcFundClassName.length() == 0)) {
			sanctionCacheModel.srcFundClassName = null;
		}

		sanctionCacheModel.destFundClassPK = getDestFundClassPK();

		sanctionCacheModel.destFundClassName = getDestFundClassName();

		String destFundClassName = sanctionCacheModel.destFundClassName;

		if ((destFundClassName != null) && (destFundClassName.length() == 0)) {
			sanctionCacheModel.destFundClassName = null;
		}

		return sanctionCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(39);

		sb.append("{sanctionId=");
		sb.append(getSanctionId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", memberId=");
		sb.append(getMemberId());
		sb.append(", budgetPeriodId=");
		sb.append(getBudgetPeriodId());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", shortDescription=");
		sb.append(getShortDescription());
		sb.append(", sanctionTypeId=");
		sb.append(getSanctionTypeId());
		sb.append(", sittingId=");
		sb.append(getSittingId());
		sb.append(", amount=");
		sb.append(getAmount());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", srcFundClassPK=");
		sb.append(getSrcFundClassPK());
		sb.append(", srcFundClassName=");
		sb.append(getSrcFundClassName());
		sb.append(", destFundClassPK=");
		sb.append(getDestFundClassPK());
		sb.append(", destFundClassName=");
		sb.append(getDestFundClassName());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(61);

		sb.append("<model><model-name>");
		sb.append("cmr.fandenatech.ndjangui.model.Sanction");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>sanctionId</column-name><column-value><![CDATA[");
		sb.append(getSanctionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>memberId</column-name><column-value><![CDATA[");
		sb.append(getMemberId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>budgetPeriodId</column-name><column-value><![CDATA[");
		sb.append(getBudgetPeriodId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>shortDescription</column-name><column-value><![CDATA[");
		sb.append(getShortDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sanctionTypeId</column-name><column-value><![CDATA[");
		sb.append(getSanctionTypeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sittingId</column-name><column-value><![CDATA[");
		sb.append(getSittingId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>amount</column-name><column-value><![CDATA[");
		sb.append(getAmount());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>srcFundClassPK</column-name><column-value><![CDATA[");
		sb.append(getSrcFundClassPK());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>srcFundClassName</column-name><column-value><![CDATA[");
		sb.append(getSrcFundClassName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>destFundClassPK</column-name><column-value><![CDATA[");
		sb.append(getDestFundClassPK());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>destFundClassName</column-name><column-value><![CDATA[");
		sb.append(getDestFundClassName());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Sanction.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			Sanction.class
		};
	private long _sanctionId;
	private long _userId;
	private String _userUuid;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private long _memberId;
	private long _budgetPeriodId;
	private String _name;
	private String _shortDescription;
	private long _sanctionTypeId;
	private long _sittingId;
	private double _amount;
	private int _status;
	private int _originalStatus;
	private boolean _setOriginalStatus;
	private long _srcFundClassPK;
	private String _srcFundClassName;
	private long _destFundClassPK;
	private String _destFundClassName;
	private long _columnBitmask;
	private Sanction _escapedModel;
}