/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package cmr.fandenatech.ndjangui.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BudgetPeriod service. Represents a row in the &quot;ndjangui_BudgetPeriod&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link cmr.fandenatech.ndjangui.model.impl.BudgetPeriodModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link cmr.fandenatech.ndjangui.model.impl.BudgetPeriodImpl}.
 * </p>
 *
 * @author guyw
 * @see BudgetPeriod
 * @see cmr.fandenatech.ndjangui.model.impl.BudgetPeriodImpl
 * @see cmr.fandenatech.ndjangui.model.impl.BudgetPeriodModelImpl
 * @generated
 */
public interface BudgetPeriodModel extends BaseModel<BudgetPeriod>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a budget period model instance should use the {@link BudgetPeriod} interface instead.
	 */

	/**
	 * Returns the primary key of this budget period.
	 *
	 * @return the primary key of this budget period
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this budget period.
	 *
	 * @param primaryKey the primary key of this budget period
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the budget period ID of this budget period.
	 *
	 * @return the budget period ID of this budget period
	 */
	public long getBudgetPeriodId();

	/**
	 * Sets the budget period ID of this budget period.
	 *
	 * @param budgetPeriodId the budget period ID of this budget period
	 */
	public void setBudgetPeriodId(long budgetPeriodId);

	/**
	 * Returns the user ID of this budget period.
	 *
	 * @return the user ID of this budget period
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this budget period.
	 *
	 * @param userId the user ID of this budget period
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this budget period.
	 *
	 * @return the user uuid of this budget period
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this budget period.
	 *
	 * @param userUuid the user uuid of this budget period
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the group ID of this budget period.
	 *
	 * @return the group ID of this budget period
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this budget period.
	 *
	 * @param groupId the group ID of this budget period
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this budget period.
	 *
	 * @return the company ID of this budget period
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this budget period.
	 *
	 * @param companyId the company ID of this budget period
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user name of this budget period.
	 *
	 * @return the user name of this budget period
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this budget period.
	 *
	 * @param userName the user name of this budget period
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this budget period.
	 *
	 * @return the create date of this budget period
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this budget period.
	 *
	 * @param createDate the create date of this budget period
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this budget period.
	 *
	 * @return the modified date of this budget period
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this budget period.
	 *
	 * @param modifiedDate the modified date of this budget period
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this budget period.
	 *
	 * @return the name of this budget period
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this budget period.
	 *
	 * @param name the name of this budget period
	 */
	public void setName(String name);

	/**
	 * Returns the short description of this budget period.
	 *
	 * @return the short description of this budget period
	 */
	@AutoEscape
	public String getShortDescription();

	/**
	 * Sets the short description of this budget period.
	 *
	 * @param shortDescription the short description of this budget period
	 */
	public void setShortDescription(String shortDescription);

	/**
	 * Returns the start date of this budget period.
	 *
	 * @return the start date of this budget period
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this budget period.
	 *
	 * @param startDate the start date of this budget period
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this budget period.
	 *
	 * @return the end date of this budget period
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this budget period.
	 *
	 * @param endDate the end date of this budget period
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the status of this budget period.
	 *
	 * @return the status of this budget period
	 */
	public int getStatus();

	/**
	 * Sets the status of this budget period.
	 *
	 * @param status the status of this budget period
	 */
	public void setStatus(int status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		cmr.fandenatech.ndjangui.model.BudgetPeriod budgetPeriod);

	@Override
	public int hashCode();

	@Override
	public CacheModel<cmr.fandenatech.ndjangui.model.BudgetPeriod> toCacheModel();

	@Override
	public cmr.fandenatech.ndjangui.model.BudgetPeriod toEscapedModel();

	@Override
	public cmr.fandenatech.ndjangui.model.BudgetPeriod toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}