/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package cmr.fandenatech.ndjangui.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the MemberFund service. Represents a row in the &quot;ndjangui_MemberFund&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link cmr.fandenatech.ndjangui.model.impl.MemberFundModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link cmr.fandenatech.ndjangui.model.impl.MemberFundImpl}.
 * </p>
 *
 * @author guyw
 * @see MemberFund
 * @see cmr.fandenatech.ndjangui.model.impl.MemberFundImpl
 * @see cmr.fandenatech.ndjangui.model.impl.MemberFundModelImpl
 * @generated
 */
public interface MemberFundModel extends BaseModel<MemberFund>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a member fund model instance should use the {@link MemberFund} interface instead.
	 */

	/**
	 * Returns the primary key of this member fund.
	 *
	 * @return the primary key of this member fund
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this member fund.
	 *
	 * @param primaryKey the primary key of this member fund
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the member fund ID of this member fund.
	 *
	 * @return the member fund ID of this member fund
	 */
	public long getMemberFundId();

	/**
	 * Sets the member fund ID of this member fund.
	 *
	 * @param memberFundId the member fund ID of this member fund
	 */
	public void setMemberFundId(long memberFundId);

	/**
	 * Returns the user ID of this member fund.
	 *
	 * @return the user ID of this member fund
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this member fund.
	 *
	 * @param userId the user ID of this member fund
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this member fund.
	 *
	 * @return the user uuid of this member fund
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this member fund.
	 *
	 * @param userUuid the user uuid of this member fund
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the group ID of this member fund.
	 *
	 * @return the group ID of this member fund
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this member fund.
	 *
	 * @param groupId the group ID of this member fund
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this member fund.
	 *
	 * @return the company ID of this member fund
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this member fund.
	 *
	 * @param companyId the company ID of this member fund
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user name of this member fund.
	 *
	 * @return the user name of this member fund
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this member fund.
	 *
	 * @param userName the user name of this member fund
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this member fund.
	 *
	 * @return the create date of this member fund
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this member fund.
	 *
	 * @param createDate the create date of this member fund
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this member fund.
	 *
	 * @return the modified date of this member fund
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this member fund.
	 *
	 * @param modifiedDate the modified date of this member fund
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the member ID of this member fund.
	 *
	 * @return the member ID of this member fund
	 */
	public long getMemberId();

	/**
	 * Sets the member ID of this member fund.
	 *
	 * @param memberId the member ID of this member fund
	 */
	public void setMemberId(long memberId);

	/**
	 * Returns the fund ID of this member fund.
	 *
	 * @return the fund ID of this member fund
	 */
	public long getFundId();

	/**
	 * Sets the fund ID of this member fund.
	 *
	 * @param fundId the fund ID of this member fund
	 */
	public void setFundId(long fundId);

	/**
	 * Returns the member name of this member fund.
	 *
	 * @return the member name of this member fund
	 */
	@AutoEscape
	public String getMemberName();

	/**
	 * Sets the member name of this member fund.
	 *
	 * @param memberName the member name of this member fund
	 */
	public void setMemberName(String memberName);

	/**
	 * Returns the fund name of this member fund.
	 *
	 * @return the fund name of this member fund
	 */
	@AutoEscape
	public String getFundName();

	/**
	 * Sets the fund name of this member fund.
	 *
	 * @param fundName the fund name of this member fund
	 */
	public void setFundName(String fundName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(cmr.fandenatech.ndjangui.model.MemberFund memberFund);

	@Override
	public int hashCode();

	@Override
	public CacheModel<cmr.fandenatech.ndjangui.model.MemberFund> toCacheModel();

	@Override
	public cmr.fandenatech.ndjangui.model.MemberFund toEscapedModel();

	@Override
	public cmr.fandenatech.ndjangui.model.MemberFund toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}