/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package cmr.fandenatech.ndjangui.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Operation_Fund service. Represents a row in the &quot;ndjangui_Operation_Fund&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link cmr.fandenatech.ndjangui.model.impl.Operation_FundModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link cmr.fandenatech.ndjangui.model.impl.Operation_FundImpl}.
 * </p>
 *
 * @author guyw
 * @see Operation_Fund
 * @see cmr.fandenatech.ndjangui.model.impl.Operation_FundImpl
 * @see cmr.fandenatech.ndjangui.model.impl.Operation_FundModelImpl
 * @generated
 */
public interface Operation_FundModel extends BaseModel<Operation_Fund>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a operation_ fund model instance should use the {@link Operation_Fund} interface instead.
	 */

	/**
	 * Returns the primary key of this operation_ fund.
	 *
	 * @return the primary key of this operation_ fund
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this operation_ fund.
	 *
	 * @param primaryKey the primary key of this operation_ fund
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the operation fund ID of this operation_ fund.
	 *
	 * @return the operation fund ID of this operation_ fund
	 */
	public long getOperationFundId();

	/**
	 * Sets the operation fund ID of this operation_ fund.
	 *
	 * @param operationFundId the operation fund ID of this operation_ fund
	 */
	public void setOperationFundId(long operationFundId);

	/**
	 * Returns the user ID of this operation_ fund.
	 *
	 * @return the user ID of this operation_ fund
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this operation_ fund.
	 *
	 * @param userId the user ID of this operation_ fund
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this operation_ fund.
	 *
	 * @return the user uuid of this operation_ fund
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this operation_ fund.
	 *
	 * @param userUuid the user uuid of this operation_ fund
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the group ID of this operation_ fund.
	 *
	 * @return the group ID of this operation_ fund
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this operation_ fund.
	 *
	 * @param groupId the group ID of this operation_ fund
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this operation_ fund.
	 *
	 * @return the company ID of this operation_ fund
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this operation_ fund.
	 *
	 * @param companyId the company ID of this operation_ fund
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user name of this operation_ fund.
	 *
	 * @return the user name of this operation_ fund
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this operation_ fund.
	 *
	 * @param userName the user name of this operation_ fund
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this operation_ fund.
	 *
	 * @return the create date of this operation_ fund
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this operation_ fund.
	 *
	 * @param createDate the create date of this operation_ fund
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this operation_ fund.
	 *
	 * @return the modified date of this operation_ fund
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this operation_ fund.
	 *
	 * @param modifiedDate the modified date of this operation_ fund
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the operation ID of this operation_ fund.
	 *
	 * @return the operation ID of this operation_ fund
	 */
	public long getOperationId();

	/**
	 * Sets the operation ID of this operation_ fund.
	 *
	 * @param operationId the operation ID of this operation_ fund
	 */
	public void setOperationId(long operationId);

	/**
	 * Returns the src fund class p k of this operation_ fund.
	 *
	 * @return the src fund class p k of this operation_ fund
	 */
	public long getSrcFundClassPK();

	/**
	 * Sets the src fund class p k of this operation_ fund.
	 *
	 * @param srcFundClassPK the src fund class p k of this operation_ fund
	 */
	public void setSrcFundClassPK(long srcFundClassPK);

	/**
	 * Returns the src fund class name of this operation_ fund.
	 *
	 * @return the src fund class name of this operation_ fund
	 */
	@AutoEscape
	public String getSrcFundClassName();

	/**
	 * Sets the src fund class name of this operation_ fund.
	 *
	 * @param srcFundClassName the src fund class name of this operation_ fund
	 */
	public void setSrcFundClassName(String srcFundClassName);

	/**
	 * Returns the dest fund class p k of this operation_ fund.
	 *
	 * @return the dest fund class p k of this operation_ fund
	 */
	public long getDestFundClassPK();

	/**
	 * Sets the dest fund class p k of this operation_ fund.
	 *
	 * @param destFundClassPK the dest fund class p k of this operation_ fund
	 */
	public void setDestFundClassPK(long destFundClassPK);

	/**
	 * Returns the dest fund class name of this operation_ fund.
	 *
	 * @return the dest fund class name of this operation_ fund
	 */
	@AutoEscape
	public String getDestFundClassName();

	/**
	 * Sets the dest fund class name of this operation_ fund.
	 *
	 * @param destFundClassName the dest fund class name of this operation_ fund
	 */
	public void setDestFundClassName(String destFundClassName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		cmr.fandenatech.ndjangui.model.Operation_Fund operation_Fund);

	@Override
	public int hashCode();

	@Override
	public CacheModel<cmr.fandenatech.ndjangui.model.Operation_Fund> toCacheModel();

	@Override
	public cmr.fandenatech.ndjangui.model.Operation_Fund toEscapedModel();

	@Override
	public cmr.fandenatech.ndjangui.model.Operation_Fund toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}