/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package cmr.fandenatech.ndjangui.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Operation service. Represents a row in the &quot;ndjangui_Operation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link cmr.fandenatech.ndjangui.model.impl.OperationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link cmr.fandenatech.ndjangui.model.impl.OperationImpl}.
 * </p>
 *
 * @author guyw
 * @see Operation
 * @see cmr.fandenatech.ndjangui.model.impl.OperationImpl
 * @see cmr.fandenatech.ndjangui.model.impl.OperationModelImpl
 * @generated
 */
public interface OperationModel extends BaseModel<Operation>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a operation model instance should use the {@link Operation} interface instead.
	 */

	/**
	 * Returns the primary key of this operation.
	 *
	 * @return the primary key of this operation
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this operation.
	 *
	 * @param primaryKey the primary key of this operation
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the operation ID of this operation.
	 *
	 * @return the operation ID of this operation
	 */
	public long getOperationId();

	/**
	 * Sets the operation ID of this operation.
	 *
	 * @param operationId the operation ID of this operation
	 */
	public void setOperationId(long operationId);

	/**
	 * Returns the user ID of this operation.
	 *
	 * @return the user ID of this operation
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this operation.
	 *
	 * @param userId the user ID of this operation
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this operation.
	 *
	 * @return the user uuid of this operation
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this operation.
	 *
	 * @param userUuid the user uuid of this operation
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the group ID of this operation.
	 *
	 * @return the group ID of this operation
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this operation.
	 *
	 * @param groupId the group ID of this operation
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this operation.
	 *
	 * @return the company ID of this operation
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this operation.
	 *
	 * @param companyId the company ID of this operation
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user name of this operation.
	 *
	 * @return the user name of this operation
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this operation.
	 *
	 * @param userName the user name of this operation
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this operation.
	 *
	 * @return the create date of this operation
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this operation.
	 *
	 * @param createDate the create date of this operation
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this operation.
	 *
	 * @return the modified date of this operation
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this operation.
	 *
	 * @param modifiedDate the modified date of this operation
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the budget period ID of this operation.
	 *
	 * @return the budget period ID of this operation
	 */
	public long getBudgetPeriodId();

	/**
	 * Sets the budget period ID of this operation.
	 *
	 * @param budgetPeriodId the budget period ID of this operation
	 */
	public void setBudgetPeriodId(long budgetPeriodId);

	/**
	 * Returns the name of this operation.
	 *
	 * @return the name of this operation
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this operation.
	 *
	 * @param name the name of this operation
	 */
	public void setName(String name);

	/**
	 * Returns the short description of this operation.
	 *
	 * @return the short description of this operation
	 */
	@AutoEscape
	public String getShortDescription();

	/**
	 * Sets the short description of this operation.
	 *
	 * @param shortDescription the short description of this operation
	 */
	public void setShortDescription(String shortDescription);

	/**
	 * Returns the operation type ID of this operation.
	 *
	 * @return the operation type ID of this operation
	 */
	public long getOperationTypeId();

	/**
	 * Sets the operation type ID of this operation.
	 *
	 * @param operationTypeId the operation type ID of this operation
	 */
	public void setOperationTypeId(long operationTypeId);

	/**
	 * Returns the sitting ID of this operation.
	 *
	 * @return the sitting ID of this operation
	 */
	public long getSittingId();

	/**
	 * Sets the sitting ID of this operation.
	 *
	 * @param sittingId the sitting ID of this operation
	 */
	public void setSittingId(long sittingId);

	/**
	 * Returns the status of this operation.
	 *
	 * @return the status of this operation
	 */
	public int getStatus();

	/**
	 * Sets the status of this operation.
	 *
	 * @param status the status of this operation
	 */
	public void setStatus(int status);

	/**
	 * Returns the amount of this operation.
	 *
	 * @return the amount of this operation
	 */
	public double getAmount();

	/**
	 * Sets the amount of this operation.
	 *
	 * @param amount the amount of this operation
	 */
	public void setAmount(double amount);

	/**
	 * Returns the src fund class p k of this operation.
	 *
	 * @return the src fund class p k of this operation
	 */
	public long getSrcFundClassPK();

	/**
	 * Sets the src fund class p k of this operation.
	 *
	 * @param srcFundClassPK the src fund class p k of this operation
	 */
	public void setSrcFundClassPK(long srcFundClassPK);

	/**
	 * Returns the src fund class name of this operation.
	 *
	 * @return the src fund class name of this operation
	 */
	@AutoEscape
	public String getSrcFundClassName();

	/**
	 * Sets the src fund class name of this operation.
	 *
	 * @param srcFundClassName the src fund class name of this operation
	 */
	public void setSrcFundClassName(String srcFundClassName);

	/**
	 * Returns the dest fund class p k of this operation.
	 *
	 * @return the dest fund class p k of this operation
	 */
	public long getDestFundClassPK();

	/**
	 * Sets the dest fund class p k of this operation.
	 *
	 * @param destFundClassPK the dest fund class p k of this operation
	 */
	public void setDestFundClassPK(long destFundClassPK);

	/**
	 * Returns the dest fund class name of this operation.
	 *
	 * @return the dest fund class name of this operation
	 */
	@AutoEscape
	public String getDestFundClassName();

	/**
	 * Sets the dest fund class name of this operation.
	 *
	 * @param destFundClassName the dest fund class name of this operation
	 */
	public void setDestFundClassName(String destFundClassName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(cmr.fandenatech.ndjangui.model.Operation operation);

	@Override
	public int hashCode();

	@Override
	public CacheModel<cmr.fandenatech.ndjangui.model.Operation> toCacheModel();

	@Override
	public cmr.fandenatech.ndjangui.model.Operation toEscapedModel();

	@Override
	public cmr.fandenatech.ndjangui.model.Operation toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}