/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package cmr.fandenatech.ndjangui.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SanctionType service. Represents a row in the &quot;ndjangui_SanctionType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link cmr.fandenatech.ndjangui.model.impl.SanctionTypeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link cmr.fandenatech.ndjangui.model.impl.SanctionTypeImpl}.
 * </p>
 *
 * @author guyw
 * @see SanctionType
 * @see cmr.fandenatech.ndjangui.model.impl.SanctionTypeImpl
 * @see cmr.fandenatech.ndjangui.model.impl.SanctionTypeModelImpl
 * @generated
 */
public interface SanctionTypeModel extends BaseModel<SanctionType>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sanction type model instance should use the {@link SanctionType} interface instead.
	 */

	/**
	 * Returns the primary key of this sanction type.
	 *
	 * @return the primary key of this sanction type
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this sanction type.
	 *
	 * @param primaryKey the primary key of this sanction type
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the sanction type ID of this sanction type.
	 *
	 * @return the sanction type ID of this sanction type
	 */
	public long getSanctionTypeId();

	/**
	 * Sets the sanction type ID of this sanction type.
	 *
	 * @param sanctionTypeId the sanction type ID of this sanction type
	 */
	public void setSanctionTypeId(long sanctionTypeId);

	/**
	 * Returns the user ID of this sanction type.
	 *
	 * @return the user ID of this sanction type
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this sanction type.
	 *
	 * @param userId the user ID of this sanction type
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this sanction type.
	 *
	 * @return the user uuid of this sanction type
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this sanction type.
	 *
	 * @param userUuid the user uuid of this sanction type
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the group ID of this sanction type.
	 *
	 * @return the group ID of this sanction type
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this sanction type.
	 *
	 * @param groupId the group ID of this sanction type
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this sanction type.
	 *
	 * @return the company ID of this sanction type
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this sanction type.
	 *
	 * @param companyId the company ID of this sanction type
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user name of this sanction type.
	 *
	 * @return the user name of this sanction type
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this sanction type.
	 *
	 * @param userName the user name of this sanction type
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this sanction type.
	 *
	 * @return the create date of this sanction type
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this sanction type.
	 *
	 * @param createDate the create date of this sanction type
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this sanction type.
	 *
	 * @return the modified date of this sanction type
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this sanction type.
	 *
	 * @param modifiedDate the modified date of this sanction type
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this sanction type.
	 *
	 * @return the name of this sanction type
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this sanction type.
	 *
	 * @param name the name of this sanction type
	 */
	public void setName(String name);

	/**
	 * Returns the short description of this sanction type.
	 *
	 * @return the short description of this sanction type
	 */
	@AutoEscape
	public String getShortDescription();

	/**
	 * Sets the short description of this sanction type.
	 *
	 * @param shortDescription the short description of this sanction type
	 */
	public void setShortDescription(String shortDescription);

	/**
	 * Returns the amount of this sanction type.
	 *
	 * @return the amount of this sanction type
	 */
	public double getAmount();

	/**
	 * Sets the amount of this sanction type.
	 *
	 * @param amount the amount of this sanction type
	 */
	public void setAmount(double amount);

	/**
	 * Returns the status of this sanction type.
	 *
	 * @return the status of this sanction type
	 */
	public int getStatus();

	/**
	 * Sets the status of this sanction type.
	 *
	 * @param status the status of this sanction type
	 */
	public void setStatus(int status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		cmr.fandenatech.ndjangui.model.SanctionType sanctionType);

	@Override
	public int hashCode();

	@Override
	public CacheModel<cmr.fandenatech.ndjangui.model.SanctionType> toCacheModel();

	@Override
	public cmr.fandenatech.ndjangui.model.SanctionType toEscapedModel();

	@Override
	public cmr.fandenatech.ndjangui.model.SanctionType toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}